HOME = "/workspace"
POS_DB_PATH = HOME+"/human_examples"                  # Your original audio files
NEG_DB_PATH = HOME+"/deezer-detector/temp_fake"      # Temporary path for restructured files
CODEC_DB_PATH = HOME+"/deezer-detector/fma_codec/"    # For codec-altered versions
WEIGHTS_PATH = HOME+"/deezer-detector/weights"        # Model checkpoints
RESULT_PATH = HOME+"/deezer-detector/results"         # Evaluation results
SPLIT_PATH = HOME+"/deezer-detector/data/dataset_split.npy"  # Train/val/test split
BR_PATH = HOME+"/deezer-detector/data/bitrates.npy"   # Bitrate information
CONF_PATH = HOME+"/deezer-detector/conf"              # Config files
